src/pmseries/GNUmakefile: pmseries needs -lpcp_pmda to avoid link error
Dependency comes from libpcp_web (which is linked with -lpcp_pmda),
but without the -lpcp_pmda the build fails when trying to link
pmseries with the message:
../../src/libpcp_web/src/libpcp_web.so: undefined reference to `pmdaCacheStore@PCP_PMDA_3.0'