Squashed 'vendor/github.com/iovisor/bcc/libbpf-tools/' changes from 971c201910..42dd86a4a4
42dd86a4a4 re-generate syscall list (add file_getattr / file_setattr)
461e977042 libbpf-tools/javagc: Include usdt.bpf.h header
45844e026c libbpf-tools: Fix list_syscalls() prototype return type
298532b0b7 libbpf-tools/biotop: Fix segmentation fault with musl libc build
41b8d76f3c Removing trailing white spaces and fixing typo (#5383)
0617cd09a0 libbpf-tools/klockstat: Disable *_nested kprobes in the fentry code
401bab86d3 libbpf-tools: trace_helpers: add str_loadavg() and str_timestamp()
ca5fb214e3 libbpf-tools/ksnoop: Remove useless and white lines (#5365)
316d0a186b syscall_helpers.c / syscall.py: update syscall list (#5363)
ac90a7a353 libbpf-tools: ksnoop: Fix two invalid access to map value (#5361)
4ea21b7f9f libbpf-tools/klockstat: Allows kprobe fallback to work with lock debugging (#5359)
044cca66ac libbpf-tools/memleak: fix typo (#5358)
2b08368955 libbpf-tools/filelife: Fix wrong full-path (#5347)
fb6040cb91 libbpf-tools: runqslower: add -c option to filter by process name prefix
6a24536b7f libbpf-tools: Fix the license for newly added path* files (#5346)
0b070eceef libbpf-tools/syscall_helpers: Modify syscall_name to return error code (#5314)
a6dcc867dc libbpf-tools/filelife: support full-path
14c4f112d4 libbpf-tools: Introduce path helpers
5064d45511 libbpf-tools/opensnoop: support mount full-path (#5333)
30b243a220 libbpf-tools/offcputime: fix min or max_block_ns unit (#5327)
ed0081c107 libbpf-tools: opensnoop: add full-path argument -F (#5323)
c242efd51d libbpf-tools/memleak: Extract print_headers (#5313)
82fe1c1fa0 libbpf-tools/biotop: Use dump_hash for map processing
132d766776 libbpf-tools/map_helpers: Add bpf_map_lookup_and_delete_batch to dump_hash
a540f7077b libbpf-tools: Fix the issue of unreleased resources
d47356a681 hardirqs: Optimize output information and increase CPU display (#5228)
2394a6d09a libbpf-tools: llcstat: Fix error: redefinition of 'key_info' on aarch64 (#5265)
240048d5f2 libbpf-tools: sigsnoop: display target process's comm (#5272)
7b47b5c0f8 libbpf-tools/drsnoop: Fix typo
706f789316 libbpf-tools: syscall_helpers.c: Fix incorrect syscall name (#5264)
ee4f1853d0 libbpf-tools: syscall_helpers.c: support loongarch64 and add more generic syscall (#5263)
8bd4e13cf8 libbpf-tools/readahead: Fix low page usage count since v5.15 (#5257)
a1988019eb libbpf-tools: statsnoop: Missing dirfd check
084d3f57b8 libbpf-tools: Adapt runqlen for struct field renaming
52cd3d03f4 libbpf-tools: Update vmlinux.h for all supported arch
03c794e9df libbpf-tools/tcptracer: Remove unused parameter 'ctx' (#5253)
a8182af095 klockstat: Don't crash on NULL ksym when looping over stack
905189b275 klockstat: Track IOCTL numbers
414dd05cc9 libbpf-tools/memleak: Change the start message to match memleak python (#5248)
ec0aa2d6d8 libbpf-tools/memleak: Allocate map and calculate statistics only when -C option is used (#5240)
e10443a464 libbpf-tools/memleak: Fix output error for invalid stackid when using combined-only mode (#5238)
470ee33f94 libbpf-tools:Fix biosnoop dependency on kernel version (#5244)
f5ccdf351c libbpf-tools/memleak: Add options to adjust stack map size (#5237)
aa0578730d libbpf-tools:Fix bitesize dependency on kernel version (#5234)
a94c0d0f21 libbpf-tools: statsnoop: Support fstat(2) and parse fd/dirfd in userspace (#5233)
58938a6a77 libbpf-tools/klockstat: Track netlink message types when taking locks (#5230)
aa1e3e4ad0 libbpf-tools/statsnoop: Display syscall name with -s
08dbab10b0 libbpf-tools: signoop: Support real-time signals (#5216)
51b251e727 libbpf-tools/klockstat: Search for correct stack offset in userspace (#5203)
710cfe8ab0 libbpf-tools/softirqs: Fix logarithmic calculation issue (#5208)
7a00c61079 libbpf-tools/hardirqs: Fix logarithmic calculation issue (#5207)
425d45f961 libbpf-tools/opensnoop: Display mode for extended fields (#5206)
862be3a407 libbpf-tools/mountsnoop: Support fsopen,fsconfig,fsmount,move_mount syscalls
b1a7d9d00c libbpf-tools/mountsnoop: Use union to pass arguments
9aa98ee782 libbpf_tools/profile: Support PID namespace mapping if available in the kernel
e73d79299b libbpf-tools/trace_helpers: Add helper to probe bpf_get_ns_current_pid_tgid
43f86c6687 libbpf-tools/profile: Add support for PID-namespacing
7ec0acbc27 libbpf-tools/slabratetop: Fix failed to create kprobe error (#5168)
9aa34c82df docs: fix a minor typo. (#5173)
3972edfc3f libbpf-tools/memleak: Fixes off-by-one error for `-Z` and `-z` option (#5149)
517ab1fa52 libbpf-tools: javagc: Hints for more information (#5154)
d43eb3da42 libbpf-tools/memleak: add mremap uprobe (#5151)
875213ffbc libbpf-tools/memleak: Fix to handle failure for invalid arguments (#5147)
ecc0a9267b libbpf-tools/memleak: mmap allocation failed, not added to pointer map (#5138)
0892f9f5d2 libbpf-tools: Allow offcputime to run on kernels without BPF trampoline
bfa5e461f2 libbpf-tools: Fix compilation error for gethostlatency
053c48df39 Add support for zfs to fsdist and fsslower tools
542ea9deed libbpf-tools/hardirqs: add `--cpu/-s` for hardirqs
d15dd2a4aa libbpf-tools/softirqs: Add `-c/--cpu` option to filter cpu
002061cd51 libbpf-tools/profile: Remove unnecessary parameter
68e2ce48b4 libbpf-tools/trace_helpers: Add a utility to split and convert string
d8055d6c30 libbpf-tools/offcputime: Add multi process/thread support
37fdd1760e libbpf-tools/profile: Fix the help message for multi process/thread
7497660214 libpf-tools/readahead: Fix attachment failure since v5.16 (#5086)
b47e9d9f54 libbpf-tools: Add flag `-Werror=undef`
9e131fca79 libbpf-tools/profile: Add additional information to backtrace for -v option
7cc8659a82 libbpf-tools/profile: Fix incorrect condition in if statement
3d4efa2bbb libbpf-tools/futexctn: Hint program is running
b4cbd29a8a libbpf-tools/offcputime: Print application starting message
d62ffe3c2d libbpf-tools/syncsnoop: Add more syscalls support
54c19abb11 libbpf-tools/sigsnoop: Allow to trace a signal list
57d6915310 libbpf-tools/javagc: Fix fatal error: 'asm/errno.h' file not found on riscv64
261968b9d6 libbpf-tools/profile: Add -f option to display output in folded format
98a6c83b01 Update tcpconnect.c
007f1cdee4 tcpconnect: increase comm field size
503bc55ab6 libbpf-tools/wakeuptime: Add offset to kernel stack trace
6a394804c2 libbpf-tools/profile: Add multi process/thread support
c1ed9c0517 libbpf-tools/futexctn: Fix some backtrace information for -v option is missing
0c0d132864 libbpf-tools/capable: Add additional information to backtrace for -v option
cdf5892726 libbpf-tools/klockstat.c: fix delete elem bug when reset stats
1fd5bfa203 libbpf-tools/bitesize.bpf.c: Fix potential out-of-bounds access in comm_allowed function fixes a potential out-of-bounds access in the comm_allowed function. Previously, the condition in the for loop checked the value of targ_comm[i] before ensuring that i is less than TASK_COMM_LEN. This could lead to out-of-bounds access if i equals TASK_COMM_LEN.
2a9efa8074 libbpf-tools/map_helpers: Fix duplicate map read operations (#4998)
cdd385c24d libbpf tcptop: Fix PID column alignment when pids are large (#5004)
5260d9a36d {libbpf-tools,tools}/vfsstat: Add unlink,mkdir,rmdir stat (#4995)
55867fa299 libbpf-tools/syscount: Fix incorrect errno usage (#4991)
ae194ff5b8 Add support for bcachefs to fsdist and fsslower tools (#4989)
6722cd334c libbpf-tools/trace_helpers: Fix incorrect DSO information in stacktrace
59e6c2b423 libbpf-tools: enforce missing-field-initializers warning and error on warnings (#4975)
2ec614c06d libbpf-tools/numamove: Add folio support (#4955)
8d19927372 libbpf-tools: add CO-RE 'syncsnoop'
3f973a70d4 libbpf-tools: Use `BPF_U[RET]PROBE` for uprobes
15f1f8b9db libbpf-tools: Support memleak trace third-part allocators
b8143de48f libbpf-tools/gethostlatency: correct section name (#4944)
08a2c041b6 fix alias detection when installed with APP_PREFIX (#4932)
7ec95016dc libbpf-tools: fix syscall tracepoints (#4920)

git-subtree-dir: vendor/github.com/iovisor/bcc/libbpf-tools
git-subtree-split: 42dd86a4a421923b51a77b63f940cb6524dce939