Ensure sys/stat.h is presented early enough in pmdalogger builds
On Mac OS X a header file warning was observed:
 In file included from event.c:18:
event.h:29: error: field 'pathstat' has incomplete type

because the sys/stat.h #include comes after the event.h #include.
Resolveed by moving the stat.h include before event.h in event.c.