src/pmdas/lmsensors/pmdalmsensors.python: fix debug option handling
This was broken in a couple ways.

1. args.debug is some sort of internal/reserved variable for some
   implementations (first seen on Ubuntu 19.04 with Python 3.7.3)
   leading to ...
       if args.debug >= 0:
   TypeError: '>=' not supported between instances of 'NoneType' and 'int'
   Fix for this appears to be to use dest=<someothername> in the
   parser.add_argument() call ... I chose <someothername> to be
   "debug_value".

2. The logic for handling the default (no -d), -d0 and -d1 (or -d2)
   cases needed to be reworked.  We cannot use default=0 because the
   default and -d0 cases are different in the code, and -d0 breaks
   the PMDA installation because the pmns and domain.h files are wrong.
   So we need to guard tests for values for args.debug_value with a
   conjuncted test if args.debug_value is defined, so instead of
   	if args.debug_value == 1
   use
   	if args.debug_value and args.debug_value == 1

Oh, and this has nothing to improve the low esteem in which I regard
Python as a development enviroment ... it simply sucks.