QA: cleanup localconfig.h build dependencies
Some QA binaries include localconfig.h but there is no explicit dependencies
between the binary build and the localconfig.h generation.
On heavily loaded systems, this can result in the binary being built
before localconf.h and a compilation error, e.g:
| username.c:8:10: fatal error: localconfig.h: No such file or directory
|     8 | #include "localconfig.h"
|       |          ^~~~~~~~~~~~~~~
| compilation terminated.

This can be reproduced by adding "sleep 30" at the start of the
localconfig.h generation rule.

Fix this by adding the missing Makefile rule dependency between the
binary (or its pre-link .o) and localconfig.h.

Also remove an un-needed scale.o->localconfig.h dependency.

Upstream-Status: Pending
Signed-off-by: Yoann Congal <yoann.congal@smile.fr>