build: remove symbol name clash on stat for Windows builds
SONGGK encountered a situation where some Windows headers are
re-defining 'stat' to _stat64, and depending on how the pmie
sources end up included we may not always have this same mis-
translation happening, and end up with:

symbol.c:69:18: error: 'SymEntry' has no member named '_stat64'; did you mean 'stat'? |

Simply picking a more meaningful name should resolve this one.