python: fix bug found by qa/739, unguarded destructor call
Need to guard the pmOptions class destructor call so that
it does not to attempt cleanup via objects that have not
been initialised yet.  Similar guards to that in pmContext
destructor prevent this failure mode:

	[...]pcp/pmapi.py", line 758, in __del__
	TypeError: 'NoneType' object is not callable