qa/common.filter: deal with changes to pmproxy warnings in _filter_pmproxy_log()
Found in pmproxy.log in CI
    Error: - EPOCH - unsupported key server (got v4, expected v5 or above)
           ^^^^^^^^^ this part seems different and was not matching
	             the old pattern