Resolve several --without-secure-sockets IPv6 build issues
auxconnect.c:757: warning: pointer targets in initialization differ in signedness
(should be unsigned char, fixed)

auxconnect.c:764: error: ‘struct sockaddr’ has no member named ‘family’
(should be sa_family, fixed)

auxconnect.c:778: error: ‘PR_AF_INET6’ undeclared (first use in this function)
auxconnect.c:775: error: ‘PR_AF_INET’ undeclared (first use in this function)
(should not use NSS/NSPR #defines here, fixed)

/* IPv6: is inet_pton supported on MINGW?? */
(looks like it, so optimistically removed conditional code - Win32 ANSI API call documented here: http://msdn.microsoft.com/en-us/library/windows/desktop/cc805844%28v=vs.85%29.aspx)

auxconnect.c:838: error: ‘__pmSockAddr’ has no member named ‘raw’
auxconnect.c:840: error: ‘__pmSockAddr’ has no member named ‘inet’
auxconnect.c:842: error: ‘__pmSockAddr’ has no member named ‘ipv6’
(missing reference to sockaddr union, fixed)