pmrep: fix infinity handling
pmrep(1) did not handle infinite values properly like other clients,
for example the expression: "tst = proc.memory.vmrss / 0" generates
exception: OverflowError: cannot convert float infinity to integer

Handle it better, and similar example to above as a regression test.