qa/check.callback.sample: try to fix false trigger
Looks like overloading of $status may have been responsible
for the script returning status != 0, but no apparent cause
reported in *.out.bad.

Seen on vm22 with lines like:
    Error: Try again. Information not currently available
in 75?.out.bad.