build/rpm/filter-requires: don't Require /usr/bin/sh
On CentOS 6.10 (vm14), I am now seeing this:
error: Failed dependencies:
    /usr/bin/sh is needed by pcp-testsuite-4.3.0-2.x86_64
when there is /bin/sh but no /usr/bin/sh.

This Requires is coming (incorrectly) from
/usr/lib/rpm/redhat/find-provides, so smack it in our fixup script.

I have no idea why this has suddenly bitten, other than possibly a
CentOS update on vm14 that was done on 2018-10-24, but QA has been
run there multiple times since then without this issue appearing,
so perhaps it is some recent tweak in the rpm building recipe that
has exposed it.