pmrep: fix use of list next operator in python3
Fix use of list next operator on arguments list, causing:

'list_iterator' object has no attribute 'next'
Traceback (most recent call last):
  File "/usr/bin/pmrep", line 1231, in <module>
    P = PMReporter()
  File "/usr/bin/pmrep", line 85, in __init__
    self.config = self.set_config_file()
  File "/usr/bin/pmrep", line 148, in set_config_file
    config = args.next()
AttributeError: 'list_iterator' object has no attribute 'next'

(picked up by new pmrep QA tests using PCP_PYTHON_PROG, win).