build: handle missing test file in test-report.py read_testlog()
The 'Parse test results' phase of CI is sometimes failing with
  File "/home/runner/work/pcp/pcp/build/ci/test-report.py", line 83, in read_testlog
    with open(os.path.join(qa_dir, test_no), encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './qa/4334'

I suspect this maybe a variant on the case handled at the end of
read_testlog, where we matched something in a failed tests output.
Handle this new scenario too and continue bravely on...