build: fix hostname dependency (again)
as noted in the comment, while UsrMerge was completed in EL 7, the
hostname package wasn't updated and still Provides: /bin/hostname

Which is not a problem for yum, but it is a problem when using dnf on
EL 7:

[root@d23f4a76502d /]# yum whatprovides /usr/bin/hostname
hostname-3.13-3.el7.x86_64 : Utility to set/show the host name or domain name
Repo        : @CentOS
Matched from:
Filename    : /usr/bin/hostname

[root@d23f4a76502d /]# dnf whatprovides /usr/bin/hostname
Error: No Matches found