sds: fix SDS_NOINIT declaration for -fno-common
SDS_NOINIT is currently declared in sds.h without extern, resulting in
multiple definitions across sds.h consumers.
With GCC 10, the default of -fcommon option will change to -fno-common,
resulting in an error:

Signed-off-by: David Disseldorp <ddiss@suse.de>